### PR TITLE
Update async_set_property_value to match the non-async version

### PR DESCRIPTION
**Pull request by crevetor**

### CODE REVIEW

**Comment by rewardone** [comment]
Is there a specific bug or deficiency that this aims to resolve? Trying to understand the specific reason for the update.

**Comment by crevetor** [comment]
Yes, I'm working on adding support for Fujitsu HVAC devices and the fact that the async version adds "SET" to the property name breaks my code. I'll have a second PR with the device stuff once this is merged.

**Comment by rewardone** [comment]
Not unwilling, I just have not had time to sit down to look at upstream changes. This code is used by (at minimum) some Home Assistant integrations. I don't think this change is a bad one, but I haven't performed regression testing for those integrations. 

Appreciate the workaround, for now.

**Comment by crevetor** [comment]
Sorry, I might have misworded this. In any case I think it will be more comfortable to not touch the main Device class for now. If you're interested I can make a new PR later on with changes that might break other device's code.

**Comment by rewardone** [comment]
At the very least, an enhancement issue referencing this PR as a way to track. The softener device override makes the same change, so it would make more sense for vacuum or generic devices to override, if needed, so that the prevailing code does not have to be duplicated. 

Will need to check with an Ayla SharkIQ dev since I don't have one of those devices.

**Pull request closed without merging**
