### PR TITLE
Add ability to poll when setting a value

### PR DESCRIPTION
**Pull request by crevetor**
This patch adds the ability to poll the last datapoint of a value after it is set to monitor for a value change (as well as "echo" going from false to true). This is used when requesting an update from the device in order to wait for the device to have updated the value in the cloud.

### CODE REVIEW

**Comment by rewardone** [comment]
Not opposed to having this code as it assists you with your device. I do question whether it is strictly necessary though. 

When you build the integration in Home Assistant, the update_coordinator will update at a frequency of your choosing (assuming a cloud polling device). I don't think your integration will need its own polling code. 

What are your thoughts?

**Comment by crevetor** [comment]
Here is how it works to update the sensed temperature :
* update property get_prop to 1 (this is the way to ask the device to update the display_temperature property)
* poll the datapoints for the get_prop property until the value changes back to 0 (which indicates the device has updated the value of display_temperature)

So the problem is that if we only do step 1 in the update code the display_temperature property that we would use would be the old value. We could live with the one update cycle delay but I think it would be better to use this poll method (only for the display_temperature property).

**Comment by rewardone** [comment]
There are a few ways to accomplish this, but I think you're choosing a harder and more complicated route. 

If your update_coordinator polling time is 'short', your 'one update cycle delay' is 'short'. A few seconds maybe. 
If your update_coordinator polling time is 'long', you can specifically call .update() when the user triggers an action (e.g. 'set value', async post updated value, update())

Ultimately, it's your integration and this code doesn't affect the Ayla library, but some things to think on. Regarding some of the other comments on the HA thread, you can take a peek at any of the code in the corresponding [culligan-hacs](https://github.com/rewardone/homeassistant-culligan-water-softener) integration for how I ended up putting things together. 

I commend you for going the route of a built-in integration vs a custom as they require quite a bit of rigor in following the quality scale.

**Comment by crevetor** [comment]
Thanks for merging this. I might rework it in the future (I also don't feel great about the update process having to wait for the polling to be done and slowing it down).

**Pull request merged**
